name: Ross' Weblog
markdown: redcarpet
pygments: true
exclude: [Gemfile, Gemfile.lock, Guardfile, sass]
permalink: :title
gems: [slug-maker]
sass:
    style:  expanded  # nested|expanded|compact|compressed
    deploy_style: compressed  # nested|expanded|compact|compressed
    compile_in_place: false   # true|false